* ml_als_factorization                   
* ml_binary_classification_eval         
* ml_classification_eval                 
* ml_create_dummy_variables             
* ml_decision_tree                       
* ml_generalized_linear_regression      
* ml_gradient_boosted_trees              
* ml_kmeans                             
* ml_lda                                 
* ml_linear_regression                  
* ml_load                                
* ml_logistic_regression                
* ml_model                               
* ml_multilayer_perceptron              
* ml_naive_bayes                         
* ml_one_vs_rest                        
* ml_options                             
* ml_pca                                
* ml_prepare_dataframe                   
* ml_prepare_features                   
* ml_prepare_response_features_intercept 
* ml_random_forest                      
* ml_save                                
* ml_survival_regression                
* ml_tree_feature_importance  